key:
  k_fold: 5
  rng_seed: 0
  model_name: "roberta-base"
  embedding_method: "weight-pool"
  checkpoint_dir: "./checkpoints/debug"
  pretrained_dir: "./checkpoints/pretrained/roberta_base"

  train_method: "vanilla"
  scheduler_method: 'cosine'
  batch_size: 16
  max_epoch: 10
  weight_decay: 0.01
  optimizer_name: "AdamW"
  lr: 5e-5
  warmup_steps: 0
  embedding_layer_start: 9

  dataset_properties:
    -
      name: commonlit
      task: "reg"
      train_data_path: "../data/train.csv"
      text_column: 'text'
      loss_name: 'RMSE'
      evaluator: 'RMSE'
      log_every: 10
      eval_every: 10
      branches:
        - label
      num_classes:
        - 1


