key:
  k_fold: 5
  rng_seed: 0
  model_name: "roberta-base"
  embedding_method: "last-avg"
  checkpoint_dir: "./checkpoints/roberta_base_rmse"

  train_method: "vanilla"
  scheduler_method: 'cosine'
  batch_size: 32
  max_epoch: 10
  weight_decay: 0.01
  optimizer_name: "AdamW"
  lr: 1e-4
  warmup_proprotion: 0.1

  dataset_properties:
    -
      name: commonlit
      task: "reg"
      train_data_path: "../data/train.csv"
      text_column: 'excerpt'
      num_classes: 1
      loss_name: 'RMSE'
      evaluator: 'RMSE'
      log_every: 10


